#!/usr/bin/env node
// Build pipeline for @kaizenreport/kensho-viewer.
//
// Two outputs:
//
// 1. Static-report assets — the pre-compiled .js files that index.html
//    references via plain <script src="..."> tags. Each assets/*.jsx is
//    transpiled in place to assets/*.js via @babel/preset-react. The
//    browser does NOT need @babel/standalone at runtime. We also produce
//    assets/data-loader.js which exposes window.__KENSHO_LOAD_DATA so the
//    static `data-bridge.js` shim can call into the shared loader.
//
// 2. Embed bundle — dist/component.js + dist/component.d.ts. An ESM build
//    of the React `<KenshoViewer />` component (and the shared loader),
//    bundled with esbuild. React/ReactDOM are external peer-deps so the
//    host app picks them up.
//
// Both outputs are produced from the same set of sources so the two modes
// stay in sync.

import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transformSync } from '@babel/core';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const ASSETS = join(ROOT, 'assets');
const SRC = join(ROOT, 'src');
const DIST = join(ROOT, 'dist');

mkdirSync(ASSETS, { recursive: true });
mkdirSync(DIST, { recursive: true });

// -------------------------------------------------------------------------
// 1. Compile every .jsx in assets/ → sibling .js
// -------------------------------------------------------------------------
const files = readdirSync(ASSETS).filter(f => f.endsWith('.jsx'));
let bytesIn = 0, bytesOut = 0;
for (const f of files) {
  const src = readFileSync(join(ASSETS, f), 'utf8');
  const { code } = transformSync(src, {
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    babelrc: false,
    configFile: false,
    filename: f,
    sourceMaps: false,
    compact: false,
    comments: true,
  });
  const out = f.replace(/\.jsx$/, '.js');
  const banner = `/* Auto-generated from ${f} by packages/viewer/scripts/build.js. Edit the .jsx — DO NOT edit this file. */\n`;
  writeFileSync(join(ASSETS, out), banner + code);
  bytesIn  += Buffer.byteLength(src);
  bytesOut += Buffer.byteLength(code);
  console.log(`  ${f.padEnd(20)} → ${out}  (${(Buffer.byteLength(code)/1024).toFixed(1)} KB)`);
}

// -------------------------------------------------------------------------
// 2. Static-report data loader — wraps src/data.js into a non-module script
//    that exposes window.__KENSHO_LOAD_DATA. The static report loads this
//    via a plain <script> tag (no `type="module"`, no bundler at runtime).
//
//    The loader source itself is plain ESM, so we strip the `export` keywords
//    and wrap in an IIFE that pins the named export onto window.
// -------------------------------------------------------------------------
const dataSrc = readFileSync(join(SRC, 'data.js'), 'utf8');
// Replace `export function name(` and `export async function name(` → `function name(`.
// Then expose `loadKenshoData` (and a couple helpers) on window at the end.
const dataNoExport = dataSrc.replace(/^export\s+(async\s+function|function|const|let|var)\b/gm, '$1');
const dataLoaderJs =
  '/* Auto-generated. Wraps src/data.js for the static-report bootstrap. */\n' +
  '(function () {\n' +
  dataNoExport +
  '\nwindow.__KENSHO_LOAD_DATA = loadKenshoData;\n' +
  '})();\n';
writeFileSync(join(ASSETS, 'data-loader.js'), dataLoaderJs);
console.log(`  ${'src/data.js'.padEnd(20)} → assets/data-loader.js  (${(Buffer.byteLength(dataLoaderJs)/1024).toFixed(1)} KB)`);

// -------------------------------------------------------------------------
// 3. ESM bundle for embedding — dist/component.js + dist/component.d.ts.
//    Lazily required (esbuild is an optional dev dep — if it's not installed,
//    the static-report path still builds). Skip with --no-bundle.
// -------------------------------------------------------------------------
const skipBundle = process.argv.includes('--no-bundle');
if (!skipBundle) {
  let esbuild;
  try {
    esbuild = await import('esbuild');
  } catch (e) {
    console.warn('[kensho-viewer] esbuild not installed — skipping embed bundle.');
    console.warn('               run `pnpm add -D esbuild` inside packages/viewer/ to enable it.');
  }
  if (esbuild) {
    await esbuild.build({
      entryPoints: [join(SRC, 'component.jsx')],
      outfile: join(DIST, 'component.js'),
      bundle: true,
      format: 'esm',
      target: ['es2020'],
      platform: 'browser',
      jsx: 'automatic',
      jsxImportSource: 'react',
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      logLevel: 'info',
      minify: false,
    });
    // Copy the .d.ts (hand-written, kept tiny).
    const dts = join(SRC, 'component.d.ts');
    if (existsSync(dts)) {
      copyFileSync(dts, join(DIST, 'component.d.ts'));
    }
    console.log(`  ${'src/component.jsx'.padEnd(20)} → dist/component.js`);
  }
}

console.log(`[kensho-viewer] built ${files.length} static asset${files.length === 1 ? '' : 's'} · ${(bytesIn/1024).toFixed(1)} KB → ${(bytesOut/1024).toFixed(1)} KB`);
